### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by wtownse** [rhinstaller/hello-world-anaconda-addon#18]
I see the error below when trying to use the example.  Simply created as per the instructions ran make and modified kickstart to point to the file on a nfs share.

17:15:34,592 CRIT anaconda: Traceback (most recent call last):

  File "/sbin/anaconda", line 1370, in <module>
    anaconda._intf.setup(ksdata)

  File "/usr/lib64/python2.7/site-packages/pyanaconda/ui/gui/__init__.py", line 749, in setup
    self._actions = self.getActionClasses(self._list_hubs())

  File "/usr/lib64/python2.7/site-packages/pyanaconda/ui/gui/__init__.py", line 759, in getActionClasses
    standalones = self._collectActionClasses(self.paths["spokes"], StandaloneSpoke)

  File "/usr/lib64/python2.7/site-packages/pyanaconda/ui/__init__.py", line 159, in _collectActionClasses
    standalones.extend(collect(module_pattern, path, lambda obj: issubclass(obj, standalone_class) and \

  File "/usr/lib64/python2.7/site-packages/pyanaconda/ui/common.py", line 730, in collect
    __import__(module_pattern % mod_name)

  File "/usr/share/anaconda/addons/org_fedora_hello_world/gui/spokes/hello_world.py", line 31, in <module>
    from org_fedora_hello_world.constants import HELLO_WORLD

  File "/usr/share/anaconda/addons/org_fedora_hello_world/constants.py", line 27

    HELLO_WORLD_NAMESPACE = (*ADDONS_NAMESPACE, "HelloWorld")

                             ^

SyntaxError: invalid syntax

**Comment by jkonecny12** [comment]
Thank you for pointing this out! We will try to fix this soon but we are right now swamped by other priority work.

**Comment by VladimirSlavik** [comment]
Hi @wtownse, what was the anaconda version you used? I just tried running the addon and it works with rawhide. I think it should work with Fedora 32 too.

**Comment by VladimirSlavik** [comment]
Oh! I see what happened :-/ Check out branch `rhel7-branch` and retry your attempt. That should be the matching version of the addon code.

**Comment by VladimirSlavik** [comment]
Hello @wtownse , did that work for you? I assume silence will mean I can (later) close this, as I can't reproduce...

**Comment by wtownse** [comment]
@VladimirSlavik I tested yesterday and it works fine.  I meant to get back to you today.  Thanks for your help.

**Comment by VladimirSlavik** [comment]
You're welcome, and thank you too!
